#!/usr/bin/expect -f
#  ./ssh.exp password 192.168.1.11 id
set pass [lrange $argv 0 0]
set server [lrange $argv 1 1]
set name [lrange $argv 2 2]
set key [lrange $argv 3 3]

spawn -ignore HUP ssh $name@$server -o StrictHostKeyChecking=accept-new -f -N -L 8888:localhost:8888 -i $key
match_max 100000
expect "*?assphrase:*"
send -- "$pass\r"
send -- "\r"
interact
expect_background

send_user ">>> spawned process backgrounding successful\n"
exit 0