#!/usr/bin/expect -f

set passphrase [lrange $argv 0 0]
set server [lrange $argv 1 1]
set user [lrange $argv 2 2]
set local_port [lrange $argv 3 3]
set remote_port [lrange $argv 4 4]
set key_path [lrange $argv 5 5]
set output_path [lrange $argv 6 6]

spawn -ignore HUP ssh -v $user@$server -f -N -L $local_port:0.0.0.0:$remote_port -i $key_path -o StrictHostKeyChecking=yes -E $output_path
expect "*passphrase*"
send -- "$passphrase\r"
interact
expect_background
exit 0